# Generated by Django 3.2.2 on 2021-05-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Height',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_range', models.CharField(max_length=20, unique=True)),
                ('height_measure', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_range', models.CharField(max_length=20, unique=True)),
                ('weight_measure', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BmiCalculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('height', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.height')),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.weight')),
            ],
        ),
    ]
