# Generated by Django 3.2.2 on 2021-05-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='height',
            name='height_measure',
            field=models.CharField(choices=[('ft', 'FT'), ('inch', 'INCH')], default='ft', max_length=20),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight_measure',
            field=models.CharField(choices=[('kg', 'KG'), ('pound', 'POUND')], default='kg', max_length=20),
        ),
    ]
